services:
  database:
    image: mariadb:11.3
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-ChangeMe123}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpass}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 10
      start_period: 30s
      interval: 5s
    volumes:
      - database_data:/var/lib/mysql:rw

  app:
    build: .
    container_name: symfony_app
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "mysql://${MARIADB_USER:-app}:${MARIADB_PASSWORD:-ChangeMe123}@database:3306/${MARIADB_DATABASE:-app}?serverVersion=11.3.0-MariaDB&charset=utf8mb4"
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: ${MARIADB_USER:-app}
      DB_PASSWORD: ${MARIADB_PASSWORD:-ChangeMe123}
      DB_NAME: ${MARIADB_DATABASE:-app}

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  database_data:
