version: '3.8'

services:
  database:
    image: mariadb:11.3
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-app}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-rootpass}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw

  app:
    build: .
    container_name: symfony_app
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - database
    environment:
      DATABASE_URL: "mysql://app:!ChangeMe!@database:3306/app?serverVersion=11.3.0-MariaDB&charset=utf8mb4"
    ports:
      - "8001:8000"

volumes:
  database_data: